name: AWS Code Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3  # 最新バージョンに更新
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2  # 最新バージョンに更新
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install awscli
    - name: Run AWS CodeDeploy
      run: aws deploy create-deployment --application-name "web_app" --deployment-group-name "github_deploy_gp" --github-location repository="yuutohasegawa/aws_cd",commitId="${{ github.sha }}"
